spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    contexts: dev
  main:
    banner-mode: off

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    com.solidbeans.ctrace: INFO
    tomcat: INFO

debug: false